# CABS tape digitization metadata

[tape]
catalog_number = 607
station_code = "TCC"
reel_number = 7 # on box: #3

[tape.epoch]
start_year = 1966 # 1966-07-13 -- 1966-09-18
start_month = 7
time_zone_offset = 0

[tape.clock.generation_1]
signal_polarity_inverted = true
two_seconds_per_pulse = false
extra_hour_mark = true
discriminator_cpm = 17 # higher frequency than 0.25Hz
discriminator_extra_bins = 1
marker_cycles_per_second = 6 # almost exactly at 6 Hz
# 15 minutes of default discriminator signal - default
minute_mark_style = "one_second_mark_over_half_rate_pulses" # TODO may need to change!

# TODO: Regular hour markers fine, but no clock cycle marker!

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "TCC/607_TCC003_NG_20200806.tpc5"

[[hint]]
position = 736874
day = 194
