# CABS tape digitization metadata

[tape]
catalog_number = 613
station_code = "TCC"
reel_number = 13 # on box: #8

[tape.epoch]
start_year = 1968 # ?--?
start_month = 12
time_zone_offset = 0

[tape.clock.generation_1]
signal_polarity_inverted = true
two_seconds_per_pulse = false
extra_hour_mark = true
discriminator_cpm = 10 # 0.16 Hz - very low frequency
discriminator_extra_bins = 1
marker_cycles_per_second = 6 # almost exactly at 6 Hz
# 15 minutes of default discriminator signal - default
minute_mark_style = "one_second_mark_over_half_rate_pulses"

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "TCC/613_TCC009_NG_20200723.tpc5"

[[hint]]
position = 1331147
day = 100 # TODO find out start day
