# CABS tape digitization metadata

[tape]
catalog_number = 615
station_code = "TCC"
reel_number = 15 # on box: #11

[tape.epoch]
start_year = 1969 # ?--?
start_month = 8
time_zone_offset = 0

[tape.clock.generation_1]
signal_polarity_inverted = true
two_seconds_per_pulse = true
extra_hour_mark = true
discriminator_cpm = 11
discriminator_extra_bins = 0
discriminator_threshold = 15.0
minute_mark_style = "one_second_mark_over_half_rate_pulses"

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "TCC/615_TCC011_NG_20200723.tpc5"
