# CABS tape digitization metadata

[tape]
catalog_number = 2
station_code = "AKU"
reel_number = 2

[tape.epoch]
start_year = 1972 # 1972-09-30(?)--1972-12-09
start_month = 9
time_zone_offset = 0

[tape.clock.generation_2]
signal_polarity_inverted = false

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "AKU/002_AKU002_NG_20250114.tpc5"
