# CABS tape digitization metadata

[tape]
catalog_number = 5
station_code = "AKU"
reel_number = 5

[tape.epoch]
start_year = 1973 # 1973-05-04--1973-07-07
start_month = 5
time_zone_offset = 0

[tape.clock.generation_2]
signal_polarity_inverted = false

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "AKU/005_AKU005_NG_20250113_part1.tpc5"

