# CABS tape digitization metadata

[tape]
catalog_number = 11
station_code = "AKU"
reel_number = 11

[tape.epoch]
start_year = 1974
start_month = 9
time_zone_offset = 0

[tape.clock.generation_2]
signal_polarity_inverted = false

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "AKU/011_AKU011_NG_20190307.tpc5"

[[hint]]
# Discard span 0 - ~15 mins, cannot confirm timing
position = 38104 # 252 17:32  252:17:32 -  0.00
discard = true

[[hint]]
# Discard span 2 - ~ 40 mins, cannot confirm timing
position = 485702800 # 301 11:34  080:11:34 -  0.00
discard = true

#[[hint]] # span 1
#position = 485266592
#prune = 22 # FIXME uncertain

[[hint]]
# Discard span 3 - ~ 5.5 hrs, cannot confirm timing
position = 485988657 # 301 12:15  080:12:15 +  0.00
discard = true
