# CABS tape digitization metadata

[tape]
catalog_number = 29
station_code = "AKU"
reel_number = 29

[tape.epoch]
start_year = 1979
start_month = 5
time_zone_offset = 0

[tape.clock.generation_2]
signal_polarity_inverted = false

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "AKU/029_AKU029_NG_20190405.tpc5"
