# CABS tape digitization metadata

[tape]
catalog_number = 75
station_code = "AKU"
reel_number = 75

[tape.epoch]
start_year = 1989 # 1989-08-24 -- ?
start_month = 8
time_zone_offset = 0

[tape.clock.generation_2]
signal_polarity_inverted = true

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "AKU/075_AKU075_NG_20241121.tpc5"

