# CABS tape digitization metadata

[tape]
catalog_number = 76
station_code = "AKU"
reel_number = 76

[tape.epoch]
start_year = 1989 # 1989-11-05 -- 1990-01-19
start_month = 11
time_zone_offset = 0

[tape.clock.generation_2]
signal_polarity_inverted = true

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "AKU/076_AKU076_NG_20241031.tpc5"

