# CABS tape digitization metadata

[tape]
catalog_number = 78 
station_code = "AKU"
reel_number = 78

[tape.epoch]
start_year = 1990 # 1990-06-22--1990-09-03
start_month = 6
time_zone_offset = 0

[tape.clock.generation_2]
signal_polarity_inverted = true

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "AKU/078_AKU078_NG_20250421.tpc5"

