# CABS tape digitization metadata

[tape]
catalog_number = 79 
station_code = "AKU"
reel_number = 79

[tape.epoch]
start_year = 1990 # 1990-09-03--1990-11-15
start_month = 9
time_zone_offset = 0

[tape.clock.generation_2]
signal_polarity_inverted = true

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "AKU/079_AKU079_NG_20250421.tpc5"

