# CABS tape digitization metadata

[tape]
catalog_number = 80
station_code = "AKU"
reel_number = 80

[tape.epoch]
start_year = 1990 # 1990-11-15--1991-02-01
start_month = 11
time_zone_offset = 0

[tape.clock.generation_2]
signal_polarity_inverted = true

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "AKU/080_AKU080_NG_20250423.tpc5"

