# CABS tape digitization metadata

[tape]
catalog_number = 103
station_code = "AKU"
reel_number = 103

[tape.epoch]
start_year = 1995 # 1995-07-15--1995-10-31
start_month = 7
time_zone_offset = 0

[tape.clock.generation_2]
signal_polarity_inverted = false

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "AKU/103_AKU103_NG_20221213_part2.tpc5"

