# CABS tape digitization metadata

[tape]
catalog_number = 105
station_code = "AKU"
reel_number = 105

[tape.epoch]
start_year = 1995 # 1995-12-06--1996-02-16
start_month = 12
time_zone_offset = 0

[tape.clock.generation_2]
signal_polarity_inverted = false

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "AKU/105_AKU105_NG_20230117.tpc5"

