# CABS tape digitization metadata

[tape]
catalog_number = 107
station_code = "AKU"
reel_number = 107

[tape.epoch]
start_year = 1996 # 1996-05-02--1996-08-01
start_month = 5
time_zone_offset = 0

[tape.clock.generation_2]
signal_polarity_inverted = false

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "AKU/107_AKU107_NG_20230118.tpc5"

