# CABS tape digitization metadata

[tape]
catalog_number = 108
station_code = "AKU"
reel_number = 108

[tape.epoch]
start_year = 1996 # 1996-08-01--1996-10-12
start_month = 8
time_zone_offset = 0

[tape.clock.generation_2]
signal_polarity_inverted = false

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "AKU/108_AKU108_NG_20230126.tpc5"

[[hint]]
position = 1261330 # near start of span 0
day = 214 # shifted from 213
# days were off by one, apparently due to incorrect leap year setting at station
