# CABS tape digitization metadata

[tape]
catalog_number = 109
station_code = "AKU"
reel_number = 109

[tape.epoch]
start_year = 1996 # 1996-10-12--1997-02-12
start_month = 10
time_zone_offset = 0

[tape.clock.generation_2]
signal_polarity_inverted = false

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "AKU/109_AKU109_NG_20230126.tpc5"

