# CABS tape digitization metadata

[tape]
catalog_number = 110
station_code = "AKU"
reel_number = 110

[tape.epoch]
start_year = 1997 # 1997-02-12--1997-04-24
start_month = 2
time_zone_offset = 0

[tape.clock.generation_2]
signal_polarity_inverted = false

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "AKU/110_AKU110_NG_20230131.tpc5"

