# CABS tape digitization metadata

[tape]
catalog_number = 111
station_code = "AKU"
reel_number = 111

[tape.epoch]
start_year = 1997 # 1997-04-25--1997-06-07
start_month = 4
time_zone_offset = 0

[tape.clock.generation_2]
signal_polarity_inverted = false

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "AKU/111_AKU111_NG_20230131.tpc5"

