# CABS tape digitization metadata

[tape]
catalog_number = 112
station_code = "AKU"
reel_number = 112

[tape.epoch]
start_year = 1997 # 1997-06-07--1997-12-03
start_month = 6
time_zone_offset = 0

[tape.clock.generation_2]
signal_polarity_inverted = false

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "AKU/112_AKU112_NG_20230206.tpc5"


[[hint]] #delete span 1
#position = 000695758 #  192 16:37  192:16:37 -  0.00 false
position = 351062983 #  227 05:22  227:05:22 -  0.00 false
discard = true

[[hint]] #delete span 2
position = 351413075#  --- --:--  1c2:18:05 -  0.00 false
discard = true

