# CABS tape digitization metadata

[tape]
catalog_number = 114
station_code = "AKU"
reel_number = 114

[tape.epoch]
start_year = 1998 # 1998-02-13--1998-06-05
start_month = 2
time_zone_offset = 0

[tape.clock.generation_2]
signal_polarity_inverted = false

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "AKU/114_AKU114_NG_20230209.tpc5"

[[hint]]
position = 262804526
day = 70

[[hint]]
position = 311736310
day = 75
hour = 7
