# CABS tape digitization metadata

[tape]
catalog_number = 116
station_code = "AKU"
reel_number = 116

[tape.epoch]
start_year = 1998 # 1998-07-17--1998-09-28
start_month = 7
time_zone_offset = 0

[tape.clock.generation_2]
signal_polarity_inverted = false

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "AKU/116_AKU116_NG_20230216.tpc5"

