# CABS tape digitization metadata

[tape]
catalog_number = 119
station_code = "AKU"
reel_number = 119

[tape.epoch]
start_year = 1999 # 1999-02-19--1999-05-01
start_month = 2
time_zone_offset = 0

[tape.clock.generation_2]
signal_polarity_inverted = false

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "AKU/119_AKU119_NG_20230224.tpc5"

