# CABS tape digitization metadata

[tape]
catalog_number = 127
station_code = "AKU"
reel_number = 127

[tape.epoch]
start_year = 2000 # 2000-09-15--2000-11-25
start_month = 9
time_zone_offset = 0

[tape.clock.generation_2]
signal_polarity_inverted = false

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "AKU/127_AKU127_NG_20230420.tpc5"

