# CABS tape digitization metadata

[tape]
catalog_number = 552
station_code = "SWU"
reel_number = 4

[tape.epoch]
start_year = 1985
start_month = 8
time_zone_offset = 0

[tape.clock.generation_2]
signal_polarity_inverted = false

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "SWU/552_SWU004_NG_20200220.tpc5"

[[hint]] # span 1
position = 9256685 # 224 01:43  207:03:43 -  0.00 #9223776
day = 207

[[hint]] # span 5
position = 227739854
day = 247

[[hint]]
# Keep span 8 - timing questionable, maybe revisit
position = 247112774 # 249 04:20  249:04:20 -  0.04 false 
time_questionable = true

[[hint]]
# Discard span 12 - ~ 22 mins, noisy, cannot confirm
position = 730151305 # 320 15:05  320:15:05 + 25.77 false 
discard = true
