# CABS tape digitization metadata

[tape]
catalog_number = 557
station_code = "SWU"
reel_number = 9

[tape.epoch]
start_year = 1986
start_month = 11
time_zone_offset = 0

[tape.clock.generation_2]
signal_polarity_inverted = false

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "SWU/557_SWU009_NG_20200227.tpc5"
