# CABS tape digitization metadata

[tape]
catalog_number = 569
station_code = "SWU"
reel_number = 21

[tape.epoch]
start_year = 1989
start_month = 11
time_zone_offset = 0

[tape.clock.generation_2]
signal_polarity_inverted = false

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "SWU/569_SWU021_NG_20200316.tpc5"

#[[hint]]
# Shift span 0 by 1 day
#position = 72547 # 306 04:26  306:04:26 -  0.00
#day = 305

#[[hint]]
# Shift span 2 by 1 day
#position = 4002033 # 306 13:58  306:13:58 -  0.00
#day = 305

#[[hint]]
# Shift span 3 by 1 day
#position = 403176325 # 347 02:30  347:02:30 -  0.00
#day = 346
