# CABS tape digitization metadata

[tape]
catalog_number = 362
station_code = "KMU"
reel_number = 21

[tape.epoch]
start_year = 1971 # 1971-09-18--1971-12-01
start_month = 9
time_zone_offset = 0

[tape.clock.generation_1]
signal_polarity_inverted = true
two_seconds_per_pulse = false
extra_hour_mark = true         # hour marks seem to (sometimes) last for two minutes
discriminator_cpm = 13         # between 13 and 14 cpm, a bit closer to 13
discriminator_extra_bins = 1
marker_cycles_per_second = 7   # close to 7 Hz (perhaps ~7.2 Hz or so)
discriminator_minutes = 14     # consistently only minutes 0..13 have discriminator signal
minute_mark_style = "one_second_mark"

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "KMU/362_KMU021_NG_20250220.tpc5"

[[hint]]
position = 960753
day = 261
