# CABS tape digitization metadata

[tape]
catalog_number = 366 
station_code = "KMU"
reel_number = 25

[tape.epoch]
start_year = 1972 # 1972-07-10--1972-09-20
start_month = 7
time_zone_offset = 0

[tape.clock.generation_1]
signal_polarity_inverted = false
two_seconds_per_pulse = false
extra_hour_mark = false
discriminator_cpm = 288
discriminator_extra_bins = 5
minute_mark_style = "one_second_mark"

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "KMU/366_KMU025_NG_20250122.tpc5"
