# CABS tape digitization metadata

[tape]
catalog_number = 369
station_code = "KMU"
reel_number = 28

[tape.epoch]
start_year = 1973 # 1973-02-19--1973-05-02
start_month = 2
time_zone_offset = 0

[tape.clock.generation_1]
signal_polarity_inverted = false
two_seconds_per_pulse = false
extra_hour_mark = false
discriminator_cpm = 288
discriminator_extra_bins = 5
minute_mark_style = "one_second_mark"

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "KMU/369_KMU028_NG_20250116.tpc5"
