# CABS tape digitization metadata

[tape]
catalog_number = 371
station_code = "KMU"
reel_number = 30

[tape.epoch]
start_year = 1973 # 1973-07-14--1973-09-25
start_month = 7
time_zone_offset = 0

[tape.clock.generation_1]
signal_polarity_inverted = true
two_seconds_per_pulse = false
extra_hour_mark = true         # hour marks seem to (sometimes) last for two minutes
discriminator_cpm = 14         # between 14 and 15 cpm
discriminator_extra_bins = 1
marker_cycles_per_second = 8   # close to 8 Hz
discriminator_minutes = 14     # consistently only minutes 0..13 have discriminator signal
minute_mark_style = "one_second_mark"

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "KMU/371_KMU030_NG_20250117.tpc5"

[[hint]]
position = 683508
day = 195

[[hint]]
position = 1654695
day = 195
