# CABS tape digitization metadata

[tape]
catalog_number = 380
station_code = "KMU"
reel_number = 39

[tape.epoch]
start_year = 1975
start_month = 5
time_zone_offset = 0

[tape.clock.generation_2]
signal_polarity_inverted = false

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "KMU/380_KMU039_NG_20190829.tpc5"
