# CABS tape digitization metadata

[tape]
catalog_number = 398
station_code = "KMU"
reel_number = 58

[tape.epoch]
start_year = 1979
start_month = 3
time_zone_offset = 0

[tape.clock.generation_2]
signal_polarity_inverted = false

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "KMU/398_KMU058_NG_20191104.tpc5"
