# CABS tape digitization metadata

[tape]
catalog_number = 407
station_code = "KMU"
reel_number = 67

[tape.epoch]
start_year = 1982
start_month = 1
time_zone_offset = 0

[tape.clock.generation_2]
signal_polarity_inverted = true

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "KMU/407_KMU067_NG_20191125.tpc5"

[[hint]]
# Discard span 1 - ~8 mins, no reasonable timestamps
position = 35839950
discard = true

[[hint]]
# Discard span 2 - ~ 19.75 hrs, cannot confirm, maybe revisit
position = 36132815 # 026 23:52  006:23:52 -  0.00
discard = true
