# CABS tape digitization metadata

[tape]
catalog_number = 426
station_code = "KMU"
reel_number = 86

[tape.epoch]
start_year = 1986 # 1986-09-02 -- 1986-12-01
start_month = 9
time_zone_offset = 0

[tape.clock.generation_2]
signal_polarity_inverted = true

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "KMU/426_KMU086_NG_20241119.tpc5"

[[hint]]
# discard span 2 - bad timestamps/Only 7 minutes long
position = 72597550
discard = true

[[hint]]
# Discard span 3 - ~ 10.75 hrs, cannot confirm, maybe revisit
position =  72784836 # 253 03:00  ---:--:-- ?
discard = true

[[hint]]
# discard span 7 - bad timestamps/only 16 minutes long
position = 497960550
discard = true

[[hint]]
# discard span 8 - ~2.25 hrs, very noisy, maybe revisit
position = 498182800
discard = true

[[hint]]
# discard span 11 - ~4.5 hrs, very noisy, maybe revisit
position = 721838450
discard = true
