# CABS tape digitization metadata

[tape]
catalog_number = 434
station_code = "KMU"
reel_number = 94

[tape.epoch]
start_year = 1988 # 1988-10-18 -- 1989-01-04
start_month = 10
time_zone_offset = 0

[tape.clock.generation_2]
signal_polarity_inverted = true

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "KMU/434_KMU094_NG_20241125.tpc5"

