# CABS tape digitization metadata

[tape]
catalog_number = 438
station_code = "KMU"
reel_number = 98

[tape.epoch]
start_year = 1989 # 1989-08-23 -- ?
start_month = 8
time_zone_offset = 0

[tape.clock.generation_2]
signal_polarity_inverted = true

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "KMU/438_KMU098_NG_20241120.tpc5"

