# CABS tape digitization metadata

[tape]
catalog_number = 442
station_code = "KMU"
reel_number = 102

[tape.epoch]
start_year = 1990 # 1990-07-13--1990-10-02
start_month = 7
time_zone_offset = 0

[tape.clock.generation_2]
signal_polarity_inverted = true

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "KMU/442_KMU102_NG_20250429.tpc5"

