# CABS tape digitization metadata

[tape]
catalog_number = 145 
station_code = "CUZ"
reel_number = 2

[tape.epoch]
start_year = 1966 # 1966-04-28--1966-07-26
start_month = 4
time_zone_offset = 0

[tape.clock.generation_1]
signal_polarity_inverted = true
two_seconds_per_pulse = true
extra_hour_mark = false
discriminator_cpm = 12
discriminator_extra_bins = 1
marker_cycles_per_second = 4   # closer to 4 than to 5 Hz
minute_mark_style = "one_second_mark"

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "CUZ/145_CUZ002_NG_20250207.tpc5"

[[hint]]
position = 219009726
day = 118
