# CABS tape digitization metadata

[tape]
catalog_number = 146
station_code = "CUZ"
reel_number = 3

[tape.epoch]
start_year = 1966 # 1966-07-26--1966-10-28 
start_month = 7
time_zone_offset = 0

[tape.clock.generation_1]
signal_polarity_inverted = true
two_seconds_per_pulse = false # true
extra_hour_mark = false
discriminator_cpm = 12
discriminator_extra_bins = 1
marker_cycles_per_second = 4   # closer to 4 than to 5 Hz
minute_mark_style = "one_second_mark"

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "CUZ/146_CUZ003_NG_20250206.tpc5"

[[hint]]
position = 167422690 # span 1
day = 207

[[hint]]
position = 173523884 # span 4
day = 208
