# CABS tape digitization metadata

[tape]
catalog_number = 147
station_code = "CUZ"
reel_number = 4

[tape.epoch]
start_year = 1966 # 1966-10-28--1967-01-18
start_month = 10
time_zone_offset = 0

[tape.clock.generation_1]
signal_polarity_inverted = true
two_seconds_per_pulse = false
extra_hour_mark = false
discriminator_cpm = 288
discriminator_extra_bins = 5
minute_mark_style = "one_second_mark"

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "CUZ/147_CUZ004_NG_20250206.tpc5"

