# CABS tape digitization metadata

[tape]
catalog_number = 149
station_code = "CUZ"
reel_number = 6

[tape.epoch]
start_year = 1967 # 1967-05-03--1967-07-27
start_month = 5
time_zone_offset = 0

[tape.clock.generation_1]
signal_polarity_inverted = true
two_seconds_per_pulse = false
extra_hour_mark = false
discriminator_cpm = 288
discriminator_extra_bins = 5
minute_mark_style = "one_second_mark"

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "CUZ/149_CUZ006_NG_20250105.tpc5"

