# CABS tape digitization metadata

[tape]
catalog_number = 151
station_code = "CUZ"
reel_number = 8

[tape.epoch]
start_year = 1967 # 1967-12-12--1968-02-24
start_month = 12
time_zone_offset = 0

[tape.clock.generation_1]
signal_polarity_inverted = true
two_seconds_per_pulse = false
extra_hour_mark = false
discriminator_cpm = 288
discriminator_extra_bins = 5
discriminator_threshold = 0.0015
minute_mark_style = "one_second_mark"

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "CUZ/151_CUZ008_NG_20250204.tpc5"

