# CABS tape digitization metadata

[tape]
catalog_number = 156
station_code = "CUZ"
reel_number = 13

[tape.epoch]
start_year = 1969 # 1969-01-19--1969-03-31
start_month = 1
time_zone_offset = 0

[tape.clock.generation_1]
signal_polarity_inverted = true
two_seconds_per_pulse = false
extra_hour_mark = false
discriminator_cpm = 288
discriminator_extra_bins = 5
discriminator_threshold = 0.0015
minute_mark_style = "one_second_mark"

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "CUZ/156_CUZ013_NG_20250123.tpc5"

