# CABS tape digitization metadata

[tape]
catalog_number = 159
station_code = "CUZ"
reel_number = 16

[tape.epoch]
start_year = 1969 # 1969-08-21--1969-11-04
start_month = 8
time_zone_offset = 0

[tape.clock.generation_1]
signal_polarity_inverted = true
two_seconds_per_pulse = false
extra_hour_mark = false
discriminator_cpm = 288
discriminator_extra_bins = 5
minute_mark_style = "one_second_mark"

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "CUZ/159_CUZ016_NG_20190924.tpc5"

