# CABS tape digitization metadata

[tape]
catalog_number = 160
station_code = "CUZ"
reel_number = 17

[tape.epoch]
start_year = 1969 # 1969-11-04--1970-01-15
start_month = 11
time_zone_offset = 0

[tape.clock.generation_1]
signal_polarity_inverted = true
two_seconds_per_pulse = false
extra_hour_mark = false # this tape has no hour markers at all
discriminator_cpm = 14
discriminator_extra_bins = 1
minute_mark_style = "one_second_mark"

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "CUZ/160_CUZ017_NG_20250128.tpc5"

[[hint]]
position = 364055
day = 308
