# CABS tape digitization metadata

[tape]
catalog_number = 162
station_code = "CUZ"
reel_number = 19

[tape.epoch]
start_year = 1970 # 1970-04-17--1970-06-28
start_month = 4
time_zone_offset = 0

[tape.clock.generation_1]
signal_polarity_inverted = true
two_seconds_per_pulse = false
extra_hour_mark = false
discriminator_cpm = 288
discriminator_extra_bins = 5
minute_mark_style = "one_second_mark"

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "CUZ/162_CUZ019_NG_20250128.tpc5"

