# CABS tape digitization metadata

[tape]
catalog_number = 164
station_code = "CUZ"
reel_number = 21

[tape.epoch]
start_year = 1970 # 1970-09-08--1970-11-18
start_month = 9
time_zone_offset = 0

[tape.clock.generation_1]
signal_polarity_inverted = true
two_seconds_per_pulse = false
extra_hour_mark = false
discriminator_cpm = 288
discriminator_extra_bins = 5
discriminator_threshold = 0.0015
minute_mark_style = "one_second_mark"

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "CUZ/164_CUZ021_NG_20250129.tpc5"

