# CABS tape digitization metadata

[tape]
catalog_number = 168
station_code = "CUZ"
reel_number = 25

[tape.epoch]
start_year = 1971 # 1971-07-28--1971-10-12
start_month = 7
time_zone_offset = 0

[tape.clock.generation_1]
signal_polarity_inverted = true
two_seconds_per_pulse = false
extra_hour_mark = false
discriminator_cpm = 288
discriminator_extra_bins = 5
minute_mark_style = "one_second_mark"

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "CUZ/168_CUZ025_NG_20250130.tpc5"

