# CABS tape digitization metadata

[tape]
catalog_number = 170
station_code = "CUZ"
reel_number = 27

[tape.epoch]
start_year = 1972 # 1972-01-05--1972-02-25
start_month = 1
time_zone_offset = 0

[tape.clock.generation_1]
signal_polarity_inverted = true
two_seconds_per_pulse = false
extra_hour_mark = false
discriminator_cpm = 15
discriminator_extra_bins = 1
marker_cycles_per_second = 6
minute_mark_style = "one_second_mark"

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "CUZ/170_CUZ027_NG_20250131.tpc5"

[[hint]]
position = 285536
day = 5

[[hint]]
position = 5006382
day = 5
