# CABS tape digitization metadata

[tape]
catalog_number = 180
station_code = "CUZ"
reel_number = 37

[tape.epoch]
start_year = 1973
start_month = 11
time_zone_offset = 0

[tape.clock.generation_2]
signal_polarity_inverted = false

#[tape.clock.generation_1]
#signal_polarity_inverted = false
#two_seconds_per_pulse = false
#extra_hour_mark = false
#discriminator_cpm = 15
#discriminator_extra_bins = 1
#discriminator_threshold = 0.1  #0.0015
#minute_mark_style = "one_second_mark"

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "CUZ/180_CUZ037_NG_20200611.tpc5"
