# CABS tape digitization metadata

[tape]
catalog_number = 193
station_code = "CUZ"
reel_number = 50

[tape.epoch]
start_year = 1976
start_month = 9
time_zone_offset = 0

[tape.clock.generation_2]
signal_polarity_inverted = false

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "CUZ/193_CUZ050_NG_20170728.tpc5"

[[hint]]
# Discard span 1 - ~ 14 mins, very noisy, bad ts
position = 340469394 # 308 18:01  308:18:00 +  0.00
discard = true
