# CABS tape digitization metadata

[tape]
catalog_number = 194
station_code = "CUZ"
reel_number = 51

[tape.epoch]
start_year = 1976
start_month = 12
time_zone_offset = 0

[tape.clock.generation_2]
signal_polarity_inverted = false

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "CUZ/194_CUZ051_NG_20170728.tpc5"
