# CABS tape digitization metadata

[tape]
catalog_number = 196
station_code = "CUZ"
reel_number = 53

[tape.epoch]
start_year = 1977
start_month = 8
time_zone_offset = 0

[tape.clock.generation_2]
signal_polarity_inverted = false

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "CUZ/196_CUZ053_NG_20170803.tpc5"
