# CABS tape digitization metadata

[tape]
catalog_number = 214
station_code = "CUZ"
reel_number = 82

[tape.epoch]
start_year = 1984
start_month = 7
time_zone_offset = 0

[tape.clock.generation_2]
signal_polarity_inverted = false

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "CUZ/214_CUZ082_NG_20171109.tpc5"

[[hint]]
# Discard span 5 - ~ 7 hrs, noisy, cannot confirm timing
position = 227903044 # 244 01:17  244:01:17 -  0.00
discard = true

[[hint]]
# Discard span 6 - ~ 53 mins, bad ts
position = 230762146 # 001 10:00  001:10:20 -  0.00
discard = true

[[hint]]
# Shift span 7 to fit calibration test
position = 231174510 # 244 09:20  244:09:20 -  0.00
day = 236

[[hint]]
# Discard span 8 - ~ 13 hrs, very very noisy, cannot confirm timing
position = 330841977 # 288 10:30  288:10:30 -  0.00
discard = true
