# CABS tape digitization metadata

[tape]
catalog_number = 221
station_code = "CUZ"
reel_number = 93

[tape.epoch]
start_year = 1987
start_month = 2
time_zone_offset = 0

[tape.clock.generation_2]
signal_polarity_inverted = false

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "CUZ/221_CUZ093_NG_20171128.tpc5"
