# CABS tape digitization metadata

[tape]
catalog_number = 475
station_code = "MAT"
reel_number = 7

[tape.epoch]
start_year = 1968 # 1968-09-04--1968-11-19
start_month = 9
time_zone_offset = 0

[tape.clock.generation_1]
signal_polarity_inverted = true
two_seconds_per_pulse = false
extra_hour_mark = false
discriminator_cpm = 13
discriminator_extra_bins = 2
discriminator_threshold = 0.001
minute_mark_style = "one_second_mark"

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "MAT/475_MAT007_NG_20250304.tpc5"

