# CABS tape digitization metadata

[tape]
catalog_number = 477
station_code = "MAT"
reel_number = 9

[tape.epoch]
start_year = 1969 # 1969-01-29--1969-04-11
start_month = 1
time_zone_offset = 0

[tape.clock.generation_1]
signal_polarity_inverted = true
two_seconds_per_pulse = false
extra_hour_mark = false
discriminator_cpm = 11
discriminator_extra_bins = 1
marker_cycles_per_second = 7
minute_mark_style = "one_second_mark"

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "MAT/477_MAT009_NG_20250303.tpc5"

[[hint]] # TEST
position = 285574058
day = 100
