# CABS tape digitization metadata

[tape]
catalog_number = 478
station_code = "MAT"
reel_number = 10

[tape.epoch]
start_year = 1969 # 1969-04-11--1969-06-20
start_month = 4
time_zone_offset = 0

[tape.clock.generation_1]
signal_polarity_inverted = true
two_seconds_per_pulse = false
extra_hour_mark = false
discriminator_cpm = 11
discriminator_extra_bins = 1
marker_cycles_per_second = 7
minute_mark_style = "one_second_mark"

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "MAT/478_MAT010_NG_20250303.tpc5"

[[hint]] # TEST
position = 657283843
day = 100

[[hint]]
position = 579114387
day = 100
