# CABS tape digitization metadata

[tape]
catalog_number = 486
station_code = "MAT"
reel_number = 18

[tape.epoch]
start_year = 1970 # 1970-11-09--1971-01-25
start_month = 11
time_zone_offset = 0

[tape.clock.generation_1]
signal_polarity_inverted = true
two_seconds_per_pulse = false
extra_hour_mark = false
discriminator_cpm = 11
discriminator_extra_bins = 1
marker_cycles_per_second = 7
minute_mark_style = "one_second_mark"

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "MAT/486_MAT018_NG_20250224.tpc5"

