# CABS tape digitization metadata

[tape]
catalog_number = 488
station_code = "MAT"
reel_number = 20

[tape.epoch]
start_year = 1971 # 1971-04-14--1971-06-27
start_month = 4
time_zone_offset = 0

[tape.clock.generation_1]
signal_polarity_inverted = true
two_seconds_per_pulse = false
extra_hour_mark = false
discriminator_cpm = 11
discriminator_extra_bins = 1
marker_cycles_per_second = 7
minute_mark_style = "one_second_mark"

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "MAT/488_MAT020_NG_20250225.tpc5"

