# CABS tape digitization metadata

[tape]
catalog_number = 499
station_code = "MAT"
reel_number = 31

[tape.epoch]
start_year = 1973 # 1973-07-15--1973-09-28
start_month = 7
time_zone_offset = 0

[tape.clock.generation_1]
signal_polarity_inverted = true
two_seconds_per_pulse = false
extra_hour_mark = false
discriminator_cpm = 420 # 7 Hz    -- 480 # 8Hz +/- 0.5 Hz
discriminator_extra_bins = 30
minute_mark_style = "one_second_mark"

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "MAT/499_MAT031_NG_20201022.tpc5"


[[hint]]
position = 15299359
day=100
