# CABS tape digitization metadata

[tape]
catalog_number = 505
station_code = "MAT"
reel_number = 37

[tape.epoch]
start_year = 1974
start_month = 10
time_zone_offset = 0

[tape.clock.generation_2]
signal_polarity_inverted = true

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "MAT/505_MAT037_NG_20180921.tpc5"
