# CABS tape digitization metadata

[tape]
catalog_number = 509
station_code = "MAT"
reel_number = 41

[tape.epoch]
start_year = 1975
start_month = 7
time_zone_offset = 0

[tape.clock.generation_2]
signal_polarity_inverted = true

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "MAT/509_MAT041_NG_20180924.tpc5"
