# CABS tape digitization metadata

[tape]
catalog_number = 510
station_code = "MAT"
reel_number = 42

[tape.epoch]
start_year = 1975
start_month = 10
time_zone_offset = 0

[tape.clock.generation_2]
signal_polarity_inverted = true

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "MAT/510_MAT042_NG_20180927.tpc5"

[[hint]]
# Discard span 8 - ~35 mins, bad ts, cannot confirm timing
position = 94536921 # 291 12:29  880:80:00 -  0.00
discard = true

[[hint]]
# Discard span 12 - ~8.5 hrs, cannot confirm timing, maybe revisit
position = 179417145 # 300 01:52  300:01:52 -  0.00
discard = true

[[hint]]
# Discard span 15 - ~8.5 hrs, cannot confirm timing, maybe revisit
position = 183541515 # 300 11:51  980:08:a8 -  0.00
discard = true
