# CABS tape digitization metadata

[tape]
catalog_number = 524
station_code = "MAT"
reel_number = 56

[tape.epoch]
start_year = 1978
start_month = 11
time_zone_offset = 0

[tape.clock.generation_2]
signal_polarity_inverted = true

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "MAT/524_MAT056_NG_20181102.tpc5"
