# CABS tape digitization metadata

[tape]
catalog_number = 536
station_code = "MAT"
reel_number = 68

[tape.epoch]
start_year = 1981 # 1981-08-02--1981-10-20 
start_month = 8
time_zone_offset = 9  # JST

[tape.clock.generation_2]
signal_polarity_inverted = true

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "MAT/536_MAT068_NG_20250402.tpc5"
