# CABS tape digitization metadata

[tape]
catalog_number = 538
station_code = "MAT"
reel_number = 70

[tape.epoch]
start_year = 1982
start_month = 1
time_zone_offset = 9  # JST

[tape.clock.generation_2]
signal_polarity_inverted = false

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "MAT/538_MAT070_NG_20171129.tpc5"
