# CABS tape digitization metadata

[tape]
catalog_number = 541
station_code = "MAT"
reel_number = 73

[tape.epoch]
start_year = 1982
start_month = 9
time_zone_offset = 9  # JST

[tape.clock.generation_2]
signal_polarity_inverted = false

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "MAT/541_MAT073_NG_20180914.tpc5"
