# CABS tape digitization metadata

[tape]
catalog_number = 545
station_code = "MAT"
reel_number = 77

[tape.epoch]
start_year = 1983
start_month = 7
time_zone_offset = 9  # JST

[tape.clock.generation_2]
signal_polarity_inverted = false

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "MAT/545_MAT077_NG_20190626.tpc5"

[[hint]]
# Discard span 0 - ~14.5 hrs, bad ts, noisy, cannot confirm
position = 1522876 # 364 21:58  000:00:04 -  0.00
discard = true
