# CABS tape digitization metadata

[tape]
catalog_number = 547
station_code = "MAT"
reel_number = 79

[tape.epoch]
start_year = 1983
start_month = 11
time_zone_offset = 9  # JST

[tape.clock.generation_2]
signal_polarity_inverted = false

[digitization]
playback_head = "NG"
channel_layout = "Standard_NG_16_Channels"
raw_data = "MAT/547_MAT079_NG_20190628.tpc5"
